192.168.16.178:
  stage: deploy
  script:
  #- ps -ef | grep server.py | grep -v grep | awk  '{print $2}' | xargs  kill -9 >/dev/null 2>&1
  - cp -r * /opt
  #- nohup python3 /home/gitlab-runner/qualitymonitoring/server.py &>/dev/null &
  only:
  - master
  tags:
  - 192.168.16.178

